export const dataList = [
  {
    log_transfer_seq: 1610165,
    transfer_data_group_seq: 81,
    transfer_data_seq: 242,
    order_no: 1350,
    transfer_job_seq: 242,
    log_start_dtm: "2025-01-01T09:00:40",
    log_end_dtm: "2025-01-22T19:00:36",
    source_name: "ข้อมูลเอกสารสิทธิที่ดิน + ข้อมูลผู้ถือกรรมสิทธิ์ (อ.ช.2)",
    source_schema: "60401",
    transfer_data_group_name: "TB_REG_PARCEL_LAND_EVIDENCE",
    target_name: "ข้อมูลตรวจสอบทรัพย์",
    schedule_mode: "CDC",
    transfer_process_status: "สำเร็จ",
    source_record: 0,
    total_record: 0,
    log_desc: "N/A",
    use_amount: 45321,
    use_unit: "ครั้ง",
    cost: 30000,
  },
  {
    log_transfer_seq: 1610164,
    transfer_data_group_seq: 58,
    transfer_data_seq: 132,
    order_no: 1349,
    transfer_job_seq: 132,
    log_start_dtm: "2025-01-01T08:30:37",
    log_end_dtm: "2025-01-22T19:00:36",
    source_name: "ข้อมูลตรวจสอบทรัพย์",
    source_schema: "60402",
    transfer_data_group_name: "TB_UDM_MAS_PARCELTYPE",
    target_name: "ข้อมูลตรวจสอบทรัพย์",
    schedule_mode: "CDC",
    transfer_process_status: "สำเร็จ",
    source_record: 0,
    total_record: 0,
    log_desc: "N/A",
    use_amount: 52000,
    use_unit: "ครั้ง",
    cost: 55000,
  },
  {
    log_transfer_seq: 1610163,
    transfer_data_group_seq: 61,
    transfer_data_seq: 135,
    order_no: 1348,
    transfer_job_seq: 135,
    log_start_dtm: "2025-01-01T09:00:35",
    log_end_dtm: "2025-01-24T19:00:36",
    source_name:
      "ข้อมูลเอกสารสิทธิที่ดิน + ข้อมูลผู้ถือกรรมสิทธิ์ (สิ่งปลูกสร้าง)",
    source_schema: "60403",
    transfer_data_group_name: "TB_SVA_SURVEYOR",
    target_name: "ข้อมูลตรวจสอบทรัพย์",
    schedule_mode: "CDC",
    transfer_process_status: "สำเร็จ",
    source_record: 3,
    total_record: 3,
    log_desc: "N/A",
    use_amount: 78000,
    use_unit: "ครั้ง",
    cost: 10000,
  },
  // {
  //     "log_transfer_seq": 1610162,
  //     "transfer_data_group_seq": 60,
  //     "transfer_data_seq": 134,
  //     "order_no": 1347,
  //     "transfer_job_seq": 134,
  //     "log_start_dtm": "2025-01-22T17:14:32",
  //     "log_end_dtm": "2025-01-22T17:14:35",
  //     "source_name": "โครงการบูรณาการระบบทะเบียนทรัพย์สิน (PIPR)",
  //     "source_schema": "SVO",
  //     "transfer_data_group_name": "TB_SVA_SURVEYJOB_ADDITION",
  //     "target_name": "ข้อมูลตรวจสอบทรัพย์",
  //     "schedule_mode": "CDC",
  //     "transfer_process_status": "สำเร็จ",
  //     "source_record": 39,
  //     "total_record": 39,
  //     "log_desc": "N/A"
  // },
  // {
  //     "log_transfer_seq": 1610161,
  //     "transfer_data_group_seq": 59,
  //     "transfer_data_seq": 133,
  //     "order_no": 1346,
  //     "transfer_job_seq": 133,
  //     "log_start_dtm": "2025-01-22T17:14:26",
  //     "log_end_dtm": "2025-01-22T17:14:31",
  //     "source_name": "โครงการบูรณาการระบบทะเบียนทรัพย์สิน (PIPR)",
  //     "source_schema": "SVO",
  //     "transfer_data_group_name": "TB_SVA_SURVEYJOB",
  //     "target_name": "ข้อมูลตรวจสอบทรัพย์",
  //     "schedule_mode": "CDC",
  //     "transfer_process_status": "สำเร็จ",
  //     "source_record": 2528,
  //     "total_record": 2528,
  //     "log_desc": "N/A"
  // },
  // {
  //     "log_transfer_seq": 1610160,
  //     "transfer_data_group_seq": 63,
  //     "transfer_data_seq": 137,
  //     "order_no": 1345,
  //     "transfer_job_seq": 137,
  //     "log_start_dtm": "2025-01-22T17:14:24",
  //     "log_end_dtm": "2025-01-22T17:14:25",
  //     "source_name": "โครงการบูรณาการระบบทะเบียนทรัพย์สิน (PIPR)",
  //     "source_schema": "SVO",
  //     "transfer_data_group_name": "TB_SVA_MAS_TYPEOFSURVEY",
  //     "target_name": "ข้อมูลตรวจสอบทรัพย์",
  //     "schedule_mode": "CDC",
  //     "transfer_process_status": "สำเร็จ",
  //     "source_record": 0,
  //     "total_record": 0,
  //     "log_desc": "N/A"
  // },
  // {
  //     "log_transfer_seq": 1610159,
  //     "transfer_data_group_seq": 50,
  //     "transfer_data_seq": 124,
  //     "order_no": 1344,
  //     "transfer_job_seq": 124,
  //     "log_start_dtm": "2025-01-22T17:14:22",
  //     "log_end_dtm": "2025-01-22T17:14:24",
  //     "source_name": "โครงการบูรณาการระบบทะเบียนทรัพย์สิน (PIPR)",
  //     "source_schema": "SVO",
  //     "transfer_data_group_name": "TB_SVA_MAS_SCALE",
  //     "target_name": "ข้อมูลตรวจสอบทรัพย์",
  //     "schedule_mode": "CDC",
  //     "transfer_process_status": "สำเร็จ",
  //     "source_record": 0,
  //     "total_record": 0,
  //     "log_desc": "N/A"
  // }
];
