[
  {
    "register_seq": 36628,
    "row_num": 1,
    "person_id": 3660100033261,
    "person_firstnameth": "ศศิธร",
    "person_middlenameth": null,
    "person_lastnameth": "เงินมั่นคง",
    "person_fullname": "ศศิธร เงินมั่นคง",
    "person_birthdate": "1979-07-14T00:00:00",
    "person_phone": "0617953642",
    "person_email": "user1@dla.go.th",
    "person_position": "นักวิชาการจัดเก็บรายได้ชำนาญการ",
    "province_seq": 53,
    "amphur_seq": 802,
    "landoffice_id": null,
    "department_seq": null,
    "department_name": null,
    "opt_seq": 5006,
    "department_phone": "056039861",
    "user_id": "user1@dla.go.th",
    "user_password": "mockhash1",
    "register_type_seq": 4,
    "approve_flag": 1,
    "register_ad_flag": null,
    "register_openid_token": null,
    "register_objective": " ",
    "remark": " ",
    "record_status": "N",
    "create_user": "1",
    "create_dtm": "2025-01-02T11:41:39",
    "last_upd_user": "13051",
    "last_upd_dtm": "2025-01-03T09:22:51",
    "landoffice_name": "อบต. ท่าฬ่อ",
    "province_name": "พิจิตร",
    "register_type_name": "จนท. (อปท.)",
    "operating_system_list": [
      { "operating_system_seq": 1, "operating_system_th": "LTAX 3000", "record_status": "Y" },
      { "operating_system_seq": 2, "operating_system_th": "LTAX Online", "record_status": "Y" }
    ]
  },
  {
    "register_seq": 36629,
    "row_num": 2,
    "person_id": 3660100033262,
    "person_firstnameth": "สมชาย",
    "person_middlenameth": null,
    "person_lastnameth": "ใจดี",
    "person_fullname": "สมชาย ใจดี",
    "person_birthdate": "1983-11-22T00:00:00",
    "person_phone": "0891234567",
    "person_email": "user2@dla.go.th",
    "person_position": "เจ้าหน้าที่การเงิน",
    "province_seq": 10,
    "amphur_seq": 101,
    "landoffice_name": "อบต. บ้านใหม่",
    "province_name": "กรุงเทพฯ",
    "register_type_name": "เจ้าหน้าที่"
  },
  {
    "register_seq": 36630,
    "row_num": 3,
    "person_id": 3660100033263,
    "person_firstnameth": "สมหญิง",
    "person_lastnameth": "สุขใจ",
    "person_fullname": "สมหญิง สุขใจ",
    "person_birthdate": "1990-03-12T00:00:00",
    "person_phone": "0812223344",
    "person_email": "user3@dla.go.th",
    "person_position": "นักวิชาการพัสดุ",
    "province_seq": 20,
    "amphur_seq": 205,
    "landoffice_name": "อบต. วังเหนือ",
    "province_name": "เชียงใหม่",
    "register_type_name": "จนท. (อปท.)"
  },
  {
    "register_seq": 36631,
    "row_num": 4,
    "person_id": 3660100033264,
    "person_firstnameth": "สุชาติ",
    "person_lastnameth": "มีสุข",
    "person_fullname": "สุชาติ มีสุข",
    "person_birthdate": "1987-06-30T00:00:00",
    "person_phone": "0823456789",
    "person_email": "user4@dla.go.th",
    "person_position": "พนักงานธุรการ",
    "province_seq": 30,
    "amphur_seq": 301,
    "landoffice_name": "อบต. ศรีนคร",
    "province_name": "นครสวรรค์",
    "register_type_name": "ผู้ใช้งานทั่วไป"
  },
  {
    "register_seq": 36632,
    "row_num": 5,
    "person_id": 3660100033265,
    "person_firstnameth": "อรทัย",
    "person_lastnameth": "แสนดี",
    "person_fullname": "อรทัย แสนดี",
    "person_birthdate": "1992-09-25T00:00:00",
    "person_phone": "0831112222",
    "person_email": "user5@dla.go.th",
    "person_position": "เจ้าหน้าที่บัญชี",
    "province_seq": 40,
    "amphur_seq": 401,
    "landoffice_name": "อบต. เมืองกลาง",
    "province_name": "ขอนแก่น",
    "register_type_name": "จนท. (อปท.)"
  },
  {
    "register_seq": 36633,
    "row_num": 6,
    "person_id": 3660100033266,
    "person_firstnameth": "กิตติ",
    "person_lastnameth": "เพียรดี",
    "person_fullname": "กิตติ เพียรดี",
    "person_birthdate": "1985-02-10T00:00:00",
    "person_phone": "0843334444",
    "person_email": "user6@dla.go.th",
    "person_position": "นักวิชาการคอมพิวเตอร์",
    "province_seq": 11,
    "amphur_seq": 110,
    "landoffice_name": "อบต. หนองบัว",
    "province_name": "ปทุมธานี",
    "register_type_name": "ผู้ดูแลระบบ"
  },
  {
    "register_seq": 36634,
    "row_num": 7,
    "person_id": 3660100033267,
    "person_firstnameth": "ชลธิชา",
    "person_lastnameth": "อารีย์",
    "person_fullname": "ชลธิชา อารีย์",
    "person_birthdate": "1995-04-19T00:00:00",
    "person_phone": "0855556666",
    "person_email": "user7@dla.go.th",
    "person_position": "พนักงานทะเบียน",
    "province_seq": 60,
    "amphur_seq": 602,
    "landoffice_name": "อบต. ลำปางเหนือ",
    "province_name": "ลำปาง",
    "register_type_name": "จนท. (อปท.)"
  },
  {
    "register_seq": 36635,
    "row_num": 8,
    "person_id": 3660100033268,
    "person_firstnameth": "วรพงษ์",
    "person_lastnameth": "จิตดี",
    "person_fullname": "วรพงษ์ จิตดี",
    "person_birthdate": "1988-08-05T00:00:00",
    "person_phone": "0867778888",
    "person_email": "user8@dla.go.th",
    "person_position": "นักวิชาการศึกษา",
    "province_seq": 70,
    "amphur_seq": 702,
    "landoffice_name": "อบต. ทุ่งนา",
    "province_name": "ราชบุรี",
    "register_type_name": "เจ้าหน้าที่"
  },
  {
    "register_seq": 36636,
    "row_num": 9,
    "person_id": 3660100033269,
    "person_firstnameth": "นฤมล",
    "person_lastnameth": "มีทรัพย์",
    "person_fullname": "นฤมล มีทรัพย์",
    "person_birthdate": "1993-12-01T00:00:00",
    "person_phone": "0879990000",
    "person_email": "user9@dla.go.th",
    "person_position": "เจ้าหน้าที่พัฒนาชุมชน",
    "province_seq": 80,
    "amphur_seq": 803,
    "landoffice_name": "อบต. หาดใหญ่",
    "province_name": "สงขลา",
    "register_type_name": "ผู้ใช้งานทั่วไป"
  },
  {
    "register_seq": 36637,
    "row_num": 10,
    "person_id": 3660100033270,
    "person_firstnameth": "ประภา",
    "person_lastnameth": "วัฒนะ",
    "person_fullname": "ประภา วัฒนะ",
    "person_birthdate": "1981-05-16T00:00:00",
    "person_phone": "0881112233",
    "person_email": "user10@dla.go.th",
    "person_position": "นักวิชาการงบประมาณ",
    "province_seq": 90,
    "amphur_seq": 902,
    "landoffice_name": "อบต. สายบุรี",
    "province_name": "ปัตตานี",
    "register_type_name": "จนท. (อปท.)"
  }
]
